<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30181" started-at="2019-06-22T12:00:10Z" finished-at="2019-06-22T12:00:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30181" started-at="2019-06-22T12:00:10Z" finished-at="2019-06-22T12:00:40Z">
      <class name="com.thoughtworks.ShopIeasy.ValidateAdminAction">
        <test-method status="PASS" signature="addProductToListasAdmin()[pri:0, instance:com.thoughtworks.ShopIeasy.ValidateAdminAction@1da2cb77]" name="addProductToListasAdmin" duration-ms="26312" started-at="2019-06-22T17:30:10Z" finished-at="2019-06-22T17:30:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProductToListasAdmin -->
        <test-method status="FAIL" signature="checkAddedProductDetails()[pri:0, instance:com.thoughtworks.ShopIeasy.ValidateAdminAction@1da2cb77]" name="checkAddedProductDetails" duration-ms="3803" started-at="2019-06-22T17:30:36Z" finished-at="2019-06-22T17:30:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.thoughtworks.ShopIeasy.ValidateAdminAction.checkAddedProductDetails(ValidateAdminAction.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAddedProductDetails -->
      </class> <!-- com.thoughtworks.ShopIeasy.ValidateAdminAction -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
